services:
  server:
    build: ./offliner
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.0"
    build: ./database
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: offliner
      MYSQL_USER: andreikars
      MYSQL_PASSWORD: andreikars
      MYSQL_ROOT_PASSWORD: andreikars
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  
      - db-data:/var/lib/mysql 
volumes:
  db-data:

